// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: v1/goods_service.proto

package goods_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductCardRequest) Reset() {
	*x = GetProductCardRequest{}
	mi := &file_v1_goods_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductCardRequest) ProtoMessage() {}

func (x *GetProductCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductCardRequest.ProtoReflect.Descriptor instead.
func (*GetProductCardRequest) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductCardRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type GetProductCardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetProductCardResponse_BarcodePending
	//	*GetProductCardResponse_Product
	Result        isGetProductCardResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductCardResponse) Reset() {
	*x = GetProductCardResponse{}
	mi := &file_v1_goods_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductCardResponse) ProtoMessage() {}

func (x *GetProductCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductCardResponse.ProtoReflect.Descriptor instead.
func (*GetProductCardResponse) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductCardResponse) GetResult() isGetProductCardResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetProductCardResponse) GetBarcodePending() string {
	if x != nil {
		if x, ok := x.Result.(*GetProductCardResponse_BarcodePending); ok {
			return x.BarcodePending
		}
	}
	return ""
}

func (x *GetProductCardResponse) GetProduct() *Product {
	if x != nil {
		if x, ok := x.Result.(*GetProductCardResponse_Product); ok {
			return x.Product
		}
	}
	return nil
}

type isGetProductCardResponse_Result interface {
	isGetProductCardResponse_Result()
}

type GetProductCardResponse_BarcodePending struct {
	BarcodePending string `protobuf:"bytes,1,opt,name=barcode_pending,json=barcodePending,proto3,oneof"`
}

type GetProductCardResponse_Product struct {
	Product *Product `protobuf:"bytes,2,opt,name=product,proto3,oneof"`
}

func (*GetProductCardResponse_BarcodePending) isGetProductCardResponse_Result() {}

func (*GetProductCardResponse_Product) isGetProductCardResponse_Result() {}

type Product struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Barcode         string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Status          int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Brands          string                 `protobuf:"bytes,4,opt,name=brands,proto3" json:"brands,omitempty"`
	Quantity        string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Categories      []string               `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	Labels          []string               `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty"`
	Allergens       []string               `protobuf:"bytes,8,rep,name=allergens,proto3" json:"allergens,omitempty"`
	Additives       []string               `protobuf:"bytes,9,rep,name=additives,proto3" json:"additives,omitempty"`
	Ingredients     []*Ingredient          `protobuf:"bytes,10,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	IngredientsText string                 `protobuf:"bytes,11,opt,name=ingredients_text,json=ingredientsText,proto3" json:"ingredients_text,omitempty"`
	Nutriments      *Nutriments            `protobuf:"bytes,12,opt,name=nutriments,proto3" json:"nutriments,omitempty"`
	NutrientLevels  *NutrientLevels        `protobuf:"bytes,13,opt,name=nutrient_levels,json=nutrientLevels,proto3" json:"nutrient_levels,omitempty"`
	Nutriscore      *Nutriscore            `protobuf:"bytes,14,opt,name=nutriscore,proto3" json:"nutriscore,omitempty"`
	NovaGroup       int32                  `protobuf:"varint,15,opt,name=nova_group,json=novaGroup,proto3" json:"nova_group,omitempty"`
	EcoscoreGrade   string                 `protobuf:"bytes,16,opt,name=ecoscore_grade,json=ecoscoreGrade,proto3" json:"ecoscore_grade,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,17,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Tags            []string               `protobuf:"bytes,18,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_v1_goods_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Product) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetBrands() string {
	if x != nil {
		return x.Brands
	}
	return ""
}

func (x *Product) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Product) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Product) GetAllergens() []string {
	if x != nil {
		return x.Allergens
	}
	return nil
}

func (x *Product) GetAdditives() []string {
	if x != nil {
		return x.Additives
	}
	return nil
}

func (x *Product) GetIngredients() []*Ingredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *Product) GetIngredientsText() string {
	if x != nil {
		return x.IngredientsText
	}
	return ""
}

func (x *Product) GetNutriments() *Nutriments {
	if x != nil {
		return x.Nutriments
	}
	return nil
}

func (x *Product) GetNutrientLevels() *NutrientLevels {
	if x != nil {
		return x.NutrientLevels
	}
	return nil
}

func (x *Product) GetNutriscore() *Nutriscore {
	if x != nil {
		return x.Nutriscore
	}
	return nil
}

func (x *Product) GetNovaGroup() int32 {
	if x != nil {
		return x.NovaGroup
	}
	return 0
}

func (x *Product) GetEcoscoreGrade() string {
	if x != nil {
		return x.EcoscoreGrade
	}
	return ""
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Nutriments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnergyKcal    float64                `protobuf:"fixed64,1,opt,name=energy_kcal,json=energyKcal,proto3" json:"energy_kcal,omitempty"`
	Fat           float64                `protobuf:"fixed64,2,opt,name=fat,proto3" json:"fat,omitempty"`
	SaturatedFat  float64                `protobuf:"fixed64,3,opt,name=saturated_fat,json=saturatedFat,proto3" json:"saturated_fat,omitempty"`
	Carbohydrates float64                `protobuf:"fixed64,4,opt,name=carbohydrates,proto3" json:"carbohydrates,omitempty"`
	Sugars        float64                `protobuf:"fixed64,5,opt,name=sugars,proto3" json:"sugars,omitempty"`
	AddedSugars   float64                `protobuf:"fixed64,6,opt,name=added_sugars,json=addedSugars,proto3" json:"added_sugars,omitempty"`
	Fiber         float64                `protobuf:"fixed64,7,opt,name=fiber,proto3" json:"fiber,omitempty"`
	Proteins      float64                `protobuf:"fixed64,8,opt,name=proteins,proto3" json:"proteins,omitempty"`
	Salt          float64                `protobuf:"fixed64,9,opt,name=salt,proto3" json:"salt,omitempty"`
	Sodium        float64                `protobuf:"fixed64,10,opt,name=sodium,proto3" json:"sodium,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nutriments) Reset() {
	*x = Nutriments{}
	mi := &file_v1_goods_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nutriments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nutriments) ProtoMessage() {}

func (x *Nutriments) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nutriments.ProtoReflect.Descriptor instead.
func (*Nutriments) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{3}
}

func (x *Nutriments) GetEnergyKcal() float64 {
	if x != nil {
		return x.EnergyKcal
	}
	return 0
}

func (x *Nutriments) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *Nutriments) GetSaturatedFat() float64 {
	if x != nil {
		return x.SaturatedFat
	}
	return 0
}

func (x *Nutriments) GetCarbohydrates() float64 {
	if x != nil {
		return x.Carbohydrates
	}
	return 0
}

func (x *Nutriments) GetSugars() float64 {
	if x != nil {
		return x.Sugars
	}
	return 0
}

func (x *Nutriments) GetAddedSugars() float64 {
	if x != nil {
		return x.AddedSugars
	}
	return 0
}

func (x *Nutriments) GetFiber() float64 {
	if x != nil {
		return x.Fiber
	}
	return 0
}

func (x *Nutriments) GetProteins() float64 {
	if x != nil {
		return x.Proteins
	}
	return 0
}

func (x *Nutriments) GetSalt() float64 {
	if x != nil {
		return x.Salt
	}
	return 0
}

func (x *Nutriments) GetSodium() float64 {
	if x != nil {
		return x.Sodium
	}
	return 0
}

type NutrientLevels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fat           string                 `protobuf:"bytes,1,opt,name=fat,proto3" json:"fat,omitempty"`
	SaturatedFat  string                 `protobuf:"bytes,2,opt,name=saturated_fat,json=saturatedFat,proto3" json:"saturated_fat,omitempty"`
	Sugars        string                 `protobuf:"bytes,3,opt,name=sugars,proto3" json:"sugars,omitempty"`
	Salt          string                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NutrientLevels) Reset() {
	*x = NutrientLevels{}
	mi := &file_v1_goods_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NutrientLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutrientLevels) ProtoMessage() {}

func (x *NutrientLevels) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutrientLevels.ProtoReflect.Descriptor instead.
func (*NutrientLevels) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{4}
}

func (x *NutrientLevels) GetFat() string {
	if x != nil {
		return x.Fat
	}
	return ""
}

func (x *NutrientLevels) GetSaturatedFat() string {
	if x != nil {
		return x.SaturatedFat
	}
	return ""
}

func (x *NutrientLevels) GetSugars() string {
	if x != nil {
		return x.Sugars
	}
	return ""
}

func (x *NutrientLevels) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

type Nutriscore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         string                 `protobuf:"bytes,1,opt,name=grade,proto3" json:"grade,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nutriscore) Reset() {
	*x = Nutriscore{}
	mi := &file_v1_goods_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nutriscore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nutriscore) ProtoMessage() {}

func (x *Nutriscore) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nutriscore.ProtoReflect.Descriptor instead.
func (*Nutriscore) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{5}
}

func (x *Nutriscore) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *Nutriscore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Ingredient struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ID              string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Text            string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	PercentEstimate float64                `protobuf:"fixed64,3,opt,name=percent_estimate,json=percentEstimate,proto3" json:"percent_estimate,omitempty"`
	Vegan           string                 `protobuf:"bytes,4,opt,name=vegan,proto3" json:"vegan,omitempty"`
	Vegetarian      string                 `protobuf:"bytes,5,opt,name=vegetarian,proto3" json:"vegetarian,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
	mi := &file_v1_goods_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient.ProtoReflect.Descriptor instead.
func (*Ingredient) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{6}
}

func (x *Ingredient) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Ingredient) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Ingredient) GetPercentEstimate() float64 {
	if x != nil {
		return x.PercentEstimate
	}
	return 0
}

func (x *Ingredient) GetVegan() string {
	if x != nil {
		return x.Vegan
	}
	return ""
}

func (x *Ingredient) GetVegetarian() string {
	if x != nil {
		return x.Vegetarian
	}
	return ""
}

type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_v1_goods_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_v1_goods_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{8}
}

func (x *SearchProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *SearchProductsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RatingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Details       map[string]float64     `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingResult) Reset() {
	*x = RatingResult{}
	mi := &file_v1_goods_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingResult) ProtoMessage() {}

func (x *RatingResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingResult.ProtoReflect.Descriptor instead.
func (*RatingResult) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{9}
}

func (x *RatingResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RatingResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RatingResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RatingResult) GetDetails() map[string]float64 {
	if x != nil {
		return x.Details
	}
	return nil
}

type ProductRatings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Ratings       []*RatingResult        `protobuf:"bytes,2,rep,name=ratings,proto3" json:"ratings,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRatings) Reset() {
	*x = ProductRatings{}
	mi := &file_v1_goods_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRatings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRatings) ProtoMessage() {}

func (x *ProductRatings) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRatings.ProtoReflect.Descriptor instead.
func (*ProductRatings) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{10}
}

func (x *ProductRatings) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *ProductRatings) GetRatings() []*RatingResult {
	if x != nil {
		return x.Ratings
	}
	return nil
}

func (x *ProductRatings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetProductRatingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRatingsRequest) Reset() {
	*x = GetProductRatingsRequest{}
	mi := &file_v1_goods_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRatingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRatingsRequest) ProtoMessage() {}

func (x *GetProductRatingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRatingsRequest.ProtoReflect.Descriptor instead.
func (*GetProductRatingsRequest) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetProductRatingsRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type GetProductRatingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ratings       *ProductRatings        `protobuf:"bytes,1,opt,name=ratings,proto3" json:"ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRatingsResponse) Reset() {
	*x = GetProductRatingsResponse{}
	mi := &file_v1_goods_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRatingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRatingsResponse) ProtoMessage() {}

func (x *GetProductRatingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_goods_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRatingsResponse.ProtoReflect.Descriptor instead.
func (*GetProductRatingsResponse) Descriptor() ([]byte, []int) {
	return file_v1_goods_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetProductRatingsResponse) GetRatings() *ProductRatings {
	if x != nil {
		return x.Ratings
	}
	return nil
}

var File_v1_goods_service_proto protoreflect.FileDescriptor

const file_v1_goods_service_proto_rawDesc = "" +
	"\n" +
	"\x16v1/goods_service.proto\x12\bgoods.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\x15GetProductCardRequest\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\"|\n" +
	"\x16GetProductCardResponse\x12)\n" +
	"\x0fbarcode_pending\x18\x01 \x01(\tH\x00R\x0ebarcodePending\x12-\n" +
	"\aproduct\x18\x02 \x01(\v2\x11.goods.v1.ProductH\x00R\aproductB\b\n" +
	"\x06result\"\x80\x05\n" +
	"\aProduct\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06brands\x18\x04 \x01(\tR\x06brands\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\x12\x16\n" +
	"\x06labels\x18\a \x03(\tR\x06labels\x12\x1c\n" +
	"\tallergens\x18\b \x03(\tR\tallergens\x12\x1c\n" +
	"\tadditives\x18\t \x03(\tR\tadditives\x126\n" +
	"\vingredients\x18\n" +
	" \x03(\v2\x14.goods.v1.IngredientR\vingredients\x12)\n" +
	"\x10ingredients_text\x18\v \x01(\tR\x0fingredientsText\x124\n" +
	"\n" +
	"nutriments\x18\f \x01(\v2\x14.goods.v1.NutrimentsR\n" +
	"nutriments\x12A\n" +
	"\x0fnutrient_levels\x18\r \x01(\v2\x18.goods.v1.NutrientLevelsR\x0enutrientLevels\x124\n" +
	"\n" +
	"nutriscore\x18\x0e \x01(\v2\x14.goods.v1.NutriscoreR\n" +
	"nutriscore\x12\x1d\n" +
	"\n" +
	"nova_group\x18\x0f \x01(\x05R\tnovaGroup\x12%\n" +
	"\x0eecoscore_grade\x18\x10 \x01(\tR\recoscoreGrade\x12\x1b\n" +
	"\timage_url\x18\x11 \x01(\tR\bimageUrl\x12\x12\n" +
	"\x04tags\x18\x12 \x03(\tR\x04tags\"\xa3\x02\n" +
	"\n" +
	"Nutriments\x12\x1f\n" +
	"\venergy_kcal\x18\x01 \x01(\x01R\n" +
	"energyKcal\x12\x10\n" +
	"\x03fat\x18\x02 \x01(\x01R\x03fat\x12#\n" +
	"\rsaturated_fat\x18\x03 \x01(\x01R\fsaturatedFat\x12$\n" +
	"\rcarbohydrates\x18\x04 \x01(\x01R\rcarbohydrates\x12\x16\n" +
	"\x06sugars\x18\x05 \x01(\x01R\x06sugars\x12!\n" +
	"\fadded_sugars\x18\x06 \x01(\x01R\vaddedSugars\x12\x14\n" +
	"\x05fiber\x18\a \x01(\x01R\x05fiber\x12\x1a\n" +
	"\bproteins\x18\b \x01(\x01R\bproteins\x12\x12\n" +
	"\x04salt\x18\t \x01(\x01R\x04salt\x12\x16\n" +
	"\x06sodium\x18\n" +
	" \x01(\x01R\x06sodium\"s\n" +
	"\x0eNutrientLevels\x12\x10\n" +
	"\x03fat\x18\x01 \x01(\tR\x03fat\x12#\n" +
	"\rsaturated_fat\x18\x02 \x01(\tR\fsaturatedFat\x12\x16\n" +
	"\x06sugars\x18\x03 \x01(\tR\x06sugars\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\tR\x04salt\"8\n" +
	"\n" +
	"Nutriscore\x12\x14\n" +
	"\x05grade\x18\x01 \x01(\tR\x05grade\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"\x91\x01\n" +
	"\n" +
	"Ingredient\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12)\n" +
	"\x10percent_estimate\x18\x03 \x01(\x01R\x0fpercentEstimate\x12\x14\n" +
	"\x05vegan\x18\x04 \x01(\tR\x05vegan\x12\x1e\n" +
	"\n" +
	"vegetarian\x18\x05 \x01(\tR\n" +
	"vegetarian\"[\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"]\n" +
	"\x16SearchProductsResponse\x12-\n" +
	"\bproducts\x18\x01 \x03(\v2\x11.goods.v1.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xc9\x01\n" +
	"\fRatingResult\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12=\n" +
	"\adetails\x18\x04 \x03(\v2#.goods.v1.RatingResult.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x97\x01\n" +
	"\x0eProductRatings\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\x120\n" +
	"\aratings\x18\x02 \x03(\v2\x16.goods.v1.RatingResultR\aratings\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"4\n" +
	"\x18GetProductRatingsRequest\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\"O\n" +
	"\x19GetProductRatingsResponse\x122\n" +
	"\aratings\x18\x01 \x01(\v2\x18.goods.v1.ProductRatingsR\aratings2\x96\x02\n" +
	"\fGoodsService\x12\\\n" +
	"\x11GetProductRatings\x12\".goods.v1.GetProductRatingsRequest\x1a#.goods.v1.GetProductRatingsResponse\x12S\n" +
	"\x0eGetProductCard\x12\x1f.goods.v1.GetProductCardRequest\x1a .goods.v1.GetProductCardResponse\x12S\n" +
	"\x0eSearchProducts\x12\x1f.goods.v1.SearchProductsRequest\x1a .goods.v1.SearchProductsResponseB\x1fZ\x1dgoods-service/api/v1;goods_v1b\x06proto3"

var (
	file_v1_goods_service_proto_rawDescOnce sync.Once
	file_v1_goods_service_proto_rawDescData []byte
)

func file_v1_goods_service_proto_rawDescGZIP() []byte {
	file_v1_goods_service_proto_rawDescOnce.Do(func() {
		file_v1_goods_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_goods_service_proto_rawDesc), len(file_v1_goods_service_proto_rawDesc)))
	})
	return file_v1_goods_service_proto_rawDescData
}

var file_v1_goods_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_v1_goods_service_proto_goTypes = []any{
	(*GetProductCardRequest)(nil),     // 0: goods.v1.GetProductCardRequest
	(*GetProductCardResponse)(nil),    // 1: goods.v1.GetProductCardResponse
	(*Product)(nil),                   // 2: goods.v1.Product
	(*Nutriments)(nil),                // 3: goods.v1.Nutriments
	(*NutrientLevels)(nil),            // 4: goods.v1.NutrientLevels
	(*Nutriscore)(nil),                // 5: goods.v1.Nutriscore
	(*Ingredient)(nil),                // 6: goods.v1.Ingredient
	(*SearchProductsRequest)(nil),     // 7: goods.v1.SearchProductsRequest
	(*SearchProductsResponse)(nil),    // 8: goods.v1.SearchProductsResponse
	(*RatingResult)(nil),              // 9: goods.v1.RatingResult
	(*ProductRatings)(nil),            // 10: goods.v1.ProductRatings
	(*GetProductRatingsRequest)(nil),  // 11: goods.v1.GetProductRatingsRequest
	(*GetProductRatingsResponse)(nil), // 12: goods.v1.GetProductRatingsResponse
	nil,                               // 13: goods.v1.RatingResult.DetailsEntry
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_v1_goods_service_proto_depIdxs = []int32{
	2,  // 0: goods.v1.GetProductCardResponse.product:type_name -> goods.v1.Product
	6,  // 1: goods.v1.Product.ingredients:type_name -> goods.v1.Ingredient
	3,  // 2: goods.v1.Product.nutriments:type_name -> goods.v1.Nutriments
	4,  // 3: goods.v1.Product.nutrient_levels:type_name -> goods.v1.NutrientLevels
	5,  // 4: goods.v1.Product.nutriscore:type_name -> goods.v1.Nutriscore
	2,  // 5: goods.v1.SearchProductsResponse.products:type_name -> goods.v1.Product
	13, // 6: goods.v1.RatingResult.details:type_name -> goods.v1.RatingResult.DetailsEntry
	9,  // 7: goods.v1.ProductRatings.ratings:type_name -> goods.v1.RatingResult
	14, // 8: goods.v1.ProductRatings.updated_at:type_name -> google.protobuf.Timestamp
	10, // 9: goods.v1.GetProductRatingsResponse.ratings:type_name -> goods.v1.ProductRatings
	11, // 10: goods.v1.GoodsService.GetProductRatings:input_type -> goods.v1.GetProductRatingsRequest
	0,  // 11: goods.v1.GoodsService.GetProductCard:input_type -> goods.v1.GetProductCardRequest
	7,  // 12: goods.v1.GoodsService.SearchProducts:input_type -> goods.v1.SearchProductsRequest
	12, // 13: goods.v1.GoodsService.GetProductRatings:output_type -> goods.v1.GetProductRatingsResponse
	1,  // 14: goods.v1.GoodsService.GetProductCard:output_type -> goods.v1.GetProductCardResponse
	8,  // 15: goods.v1.GoodsService.SearchProducts:output_type -> goods.v1.SearchProductsResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_goods_service_proto_init() }
func file_v1_goods_service_proto_init() {
	if File_v1_goods_service_proto != nil {
		return
	}
	file_v1_goods_service_proto_msgTypes[1].OneofWrappers = []any{
		(*GetProductCardResponse_BarcodePending)(nil),
		(*GetProductCardResponse_Product)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_goods_service_proto_rawDesc), len(file_v1_goods_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_goods_service_proto_goTypes,
		DependencyIndexes: file_v1_goods_service_proto_depIdxs,
		MessageInfos:      file_v1_goods_service_proto_msgTypes,
	}.Build()
	File_v1_goods_service_proto = out.File
	file_v1_goods_service_proto_goTypes = nil
	file_v1_goods_service_proto_depIdxs = nil
}
